name: bbk_ai_app
description: BBK AI app
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# (اختياري) لو حبيتي لاحقًا تشغلين السبلش تلقائي من الباكدج
# flutter_native_splash:
#   color: "#F8F2FF"
#   android_12:
#     background_color: "#F8F2FF"
#   branding_mode: bottom
