name: bbk_ai_app
description: BBK AI mobile app
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
