name: bbk_ai_app
description: BBK AI Flutter App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/splash_logo.png
    - assets/app_banner.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/app_icon.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#10366E" # الأزرق المستخدم
  image: assets/splash_logo.png
  android: true
  ios: false
  android_gravity: center
