name: bbk_ai_app
description: BBK AI Mobile Banking (Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.13.0   # OCR (placeholder بالصفحة)
  http: ^1.2.2                              # Payment placeholders
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/app_banner.png
    - assets/app_icon.png
    - assets/splash_logo.png

# أيقونة التطبيق
flutter_icons:
  android: true
  ios: false
  image_path: assets/app_icon.png
  min_sdk_android: 23
  adaptive_icon_background: "#123D7A"
  adaptive_icon_foreground: assets/app_icon.png

# شاشة الإقلاع (Splash)
flutter_native_splash:
  android: true
  ios: false
  color: "#123D7A"
  image: assets/splash_logo.png
  android_12:
    color: "#123D7A"
    image: assets/splash_logo.png
