name: bbk_ai_app
description: BBK AI Mobile app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # الأساسيات
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  url_launcher: ^6.3.0

  # الكاميرا + OCR
  camera: ^0.11.2
  google_mlkit_text_recognition: ^0.14.0

  # صور من الجهاز (اختياري مفيد)
  image_picker: ^1.1.2

  # الصلاحيات
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# أيقونة وسبلاش
flutter_launcher_icons: 
  android: true
  ios: false
  image_path: assets/ic_launcher.png
  min_sdk_android: 23

flutter_native_splash:
  color: "#F8F2FF"
  image: assets/splash_logo.png
  android: true
  ios: false
  android_gravity: center

flutter:
  uses-material-design: true
  assets:
    - assets/app_banner.png
    - assets/app_icon.png
    - assets/ic_launcher.png
    - assets/splash_logo.png
