name: bbk_ai
description: Simple OCR demo (camera/gallery + ML Kit)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # لا تحذف هالثنتين – هُم سبب الـ undefined
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2

  # UI بسيطة
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
