name: bbk_ai_app
description: BBK AI Mobile Banking
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # OCR (نصوص) – لا يعتمد على الكاميرا مباشرة
  google_mlkit_text_recognition: ^0.13.0

  # الكاميرا - ثبتناها على 0.11.2 كما اقترح حل Pub
  camera: ^0.11.2

  path_provider: ^2.1.4
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/app_banner.png
    - assets/splash_logo.png
