name: bbk_ai_app
description: BBK AI Mobile – OCR, Payments & AI Support
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  intl: ^0.19.0
  # OCR + صورة/كاميرا
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2
  camera: ^0.10.6+6
  path_provider: ^2.1.4
  path: ^1.9.0
  # دفع (حقول بطاقة + تنسيقات)
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_banner.png
    - assets/app_icon.png
    - assets/splash_logo.png
    - assets/ic_launcher.png

# أيقونة التطبيق
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 24
  remove_alpha_ios: true

# شاشة الإطلاق
flutter_native_splash:
  color: "#0F3B78"
  image: assets/splash_logo.png
  android_gravity: center
  android_12:
    image: assets/splash_logo.png
    icon_background_color: "#0F3B78"
