name: bbk_ai_app
description: BBK AI Mobile Banking demo
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_banner.png
    - assets/ic_launcher.png
    - assets/splash_logo.png
    - assets/app_icon.png
