name: bbk_ai
description: Minimal Flutter app for CI builds
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # OCR (اختياري – إذا تحتاجه فعلاً)
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # إذا عندك أصول (صور/خطوط) أضفها هنا لاحقاً:
  # assets:
  #   - assets/
