name: bbk_ai_app
description: BBK AI Mobile Banking
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.11.2+1
  path_provider: ^2.1.4
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_banner.png
    - assets/app_icon.png
    - assets/splash_logo.png

flutter_native_splash:
  color: "#0D2F63"
  image: assets/splash_logo.png
  android_12:
    image: assets/splash_logo.png
    color: "#0D2F63"

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/ic_launcher.png
  adaptive_icon_background: "#0D2F63"
  adaptive_icon_foreground: assets/ic_launcher.png
