name: Build Flutter APK

on:
  push:
    branches: [ main ]
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/**"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      # ⬇️ أهم خطوة: إنشاء مجلدات Android/iOS/Web إذا كانت ناقصة
      - name: Ensure mobile/web platforms exist
        shell: bash
        run: |
          if [ ! -d "android" ]; then
            echo "android/ not found -> running flutter create"
            flutter create . --platforms=android,ios,web
          else
            echo "android/ already exists."
          fi

      - name: Fetch packages
        run: flutter pub get

      # (اختياري) تأكيد منصّة الأندرويد موجودة داخل المشروع
      - name: Ensure Android platform inside project
        run: flutter create . --platforms=android

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: bbk-ai-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
